name: FSSI File Processor
markdown: redcarpet
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
github: [Repository metadata]
url: http://gsa.github.io/fssi-file-processor/
baseurl: /fssi-file-processor
